version: 2.1
orbs:
  circleci-cli: circleci/circleci-cli@0.1.7
  orb-tools: circleci/orb-tools@9.0.1
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - circleci-cli/install
      - run: npm test
      - run: npm run manual:tests
      - run: npm run docs

workflows:
  orb_tests:
    jobs:
    - build
    # - orb-tools/test-in-builds:
    #     checkout: true
    #     orb-location: src/orb.yml
    #     orb-name: 'cypress-io/cypress'
    #     test-steps:
    #       - run: echo 'Hello there'
